#+title: Allgemeine Modelltheorie
#+author: Prof. Dr. phil. Herbert Stachowiak
#+LANGUAGE: de

* Colophon

Prof. Dr. phil. Herbert Stachowiak
Berlin --- Paderborn

Direktor des Instituts für Wissenschafts- und Planungstheorie des Forschungs-
und Entwicklungszentrums für objektivierte Lehr- und Lernverfahren GmbH.

Das Werk ist urheberrechtlich geschützt.
Die dadurch begründeten Rechte, insbesondere die der Übersetzung,
des Nachdruckes, der Entnahme von Abbildungen,
der Funksendung, der Wiedergabe auf photomechanischem
oder ähnlichem Wege und der Speiche mng in Datenverarbeitungsanlagen,
bleiben, auch bei nur auszugsweiser Verwertung, vorbehalten.

(C) 1973 by Springer-Verlag/Wien

Library of Congress Cataiog Card Number 73-75910

Printed in Austria

ISBN 3-211-81106-0 Springer-Verlag Wien --- New York
ISBN 0-387-81106-0 Springer-Verlag New York --- Wien

* Widmung

Meinem Vater
Adalbert Stachowiak
zum Gedächtnis

* Vorwort

Die vorliegende Untersuchung ist das Ergebnis langjähriger Studien im Umkreis
des Modellbegriffs. Sie begannen 1957 mit einem ersten systematischen
Orientierungsversuch („Uber kausale, konditionale und strukturelle
Erklärungsmodelle“, Philosophia Naturalis, Bd. IV, H. 4, 1957, p. 403— 433) und
führten über mehrere Stufen fortschreitender Systematisierung zu dem 1965
vorgelegten modelltheoretischen Konzept („Gedanken zu einer allgemeinen Theorie
der Modelle“, Studium Generale, 18. Jg., H. 7, 1965, p. 432— 463), das ich
schließlich auf die Fassung der jetzt vorliegenden „Allgemeinen Modelltheorie“
erweitern und präzisieren konnte. Ende 1969 folgte ich einer Einladung der
UNESCO, Paris, eine Studie über den Modellbegriff abzufassen. Diese Arbeit ist
inzwischen erschienen in dem Sammelwerk „Scientific Thought“, Band 9 der Reihe
New Babylon (Mouton/Unesco, Paris-The Hague, 1972). Sie ist zum Teil als
Vorentwurf des dritten Kapitels der „Allgemeinen Modelltheorie“ zu betrachten.
Andere eigene Veröffentlichungen, insbesondere auf erkenntnispsychologischem und
wissenschaftstheoretischem Gebiet, sind durch die erwähnten modelltheoretischen
Untersuchungen beeinflußt. An ihren Ergebnissen ist auch mein Buch „Denken und
Erkennen im kybernetischen Modell“ (Wien — New York: Springer, 2. Aufl., 1969)
orientiert.

Mit vielen meiner Leser — kritische Rezensenten inbegriffen — betrachte ich mich
als in einem umfassenden Gesprächs- und Arbeitszusammenhang verbunden. Daher sei
auch zu dem vorliegenden Werk die Bitte um Hinweise auf systematische Fehler,
Disproportionalitäten, bedenklich scheinende Wertsetzungen und sonstige
tatsächliche oder mögliche Mängel des Buches vorgetragen. Nur in solcher
Kommunikation kann auf einem Felde, zu dessen weiterer Bearbeitung die Kräfte
eines einzelnen nicht ausreichen, der vorgelegte Ansatz bereinigt, vertieft und
erweitert werden. Allen Helfern hieran Dank im voraus.

Bei der Abfassung des Manuskripts haben mir in der Anfangsphase meiner
modelltheorerischen Überlegungen Gespräche mit den Herren P. Gäng und Prof. Dr. D.
Wunderlich wertvolle Anregungen gegeben. Hierfür sei beiden Genannten
herzlich gedankt. Herrn Wunderlich bin ich darüber hinaus für seine oft bis ins
formale Detail reichende Hilfe bei der Erarbeitung des logisch-explikativen
Teils des dritten Kapitels und der darin vorkommenden Maßbestimmungen zu
besonderem Dank verpflichtet, Den Herren Prof. Dr. H. Pachale, Dipl.-Math.
Studienrat W.Krüger und Dipl.-Math. R.-B. Lüschow dünke ich für kritische
Durchsicht des Manuskripts, Herrn Krüger darüber hinaus für gründliches
Korrekturlesen. Die Anlage des Namenverzeichnissen sowie die sorgfältige
Fehlerdurchsicht des Literaturverzeichnisses und der Bibliographie verdanke ich
Herrn H. Radimersky. Herr Dr. G.Wersig hat mir dankenswerterweise seine sich
über ein Jahr erstreckende Hilfe in bibliographischen Recherchen zureit werden
lassen. Dankbar hervorzuheben habe ich endlich erneut die unentbehrliche
technisch-organisatorische UnterStützung durch meine langjährige Mitarbeiterin
Frau H. Stranz und meine Frau B. Stachowiak-Prästel.

Die Deutsche Forschungsgemeinschaft hat meine modelltheoretischen Bemühungen in
einer (aus persönlichen Gründen kritisch gewordenen) wichtigen Arbeitsphase
unterstützt, wofür ihr hier aufrichtig Dank gesagt sei.

Dem Springer-Verlag bin ich für Verständnis, Geduld und stets freundliches
Entgegenkommen treu verbunden.

Berlin, im Sommer 1973

Herbert Stachowiak

* Einleitung

Im wissenschaftlichen wie außerwissenschaftlichen Sprachgebrauch hat gegenwärtig
der Modellbegriff zunehmend Relevanz erlangt. Bei zahlreichen passenden — leider
auch unpassenden — Gelegenheiten ist von „Modellen“ die Rede. Das Wort Modell
wird ebenso gedankenlos fehlverwendet, wie man es als bewußt gewählten
wissenschaftlichen Terminus in Zusammenhängen findet, die das Bestreben erkennen
lassen, es mit einer streng explizierten oder wenigstens explizierbaren
Bedeutung zu verbinden. In der Mathematik und Logik ist dies unter starker
Einschränkung seines Bedeutungsgehaltes realisiert, und einige Autoren, die
diese Einschränkung nicht für fruchtbar hielten, haben versucht, das Spezifische
des Modellbegriffs so zu charakterisieren, daß erkennbar wird, in welchem Sinne
sie diesen Begriff verstanden und verwendet wissen wollen. Auch Ansätze
taxionomischer Klassifikation von Modellen sind hier und dort zu finden. Bei den
meisten Autoren jedoch, die in mannigfaltigsten Bezügen von Modellen sprechen,
vermißt man weitgehend, wenn nicht gänzlich,
wissenschaftstheoretisch-methodologische Reflexion über den von ihnen zugrunde
gelegten Modellbegriff. Dessen Charakteristika können in solchen Fällen nur
indirekt aus den gebotenen Kontexten erschlossen werden.

Gerade hier aber, wo noch der mehr intuitive Zugriff des Schreibenden und
Sprechenden die Funktion normierender terminologischer Verwendungsregeln
innehat, pflegt nicht selten der Wandel der Sprachgewohnheit, indem diese sich
fast unmerklich an einen bestimmten Stil der Betrachtung und des Denkens
adaptiert, zum Indiz neu sich gestaltender allgemeiner Haltungen und
Einstellungen zu werden. Die zunehmende Neigung zeitgenössischer Forscher, sogar
Erkenntnisgebilde von der Qualität hochkomplexer erfahrungswissenschaftlicher
Theorien als ..Modelle" aufzufassen oder sie zumindesr kurzweg so zu nennen,
dürfte in diesem Sinne eine tiefliegende Wandlung
wissenschaftlich-philosophischen Denkens sichtbar werden lassen. Es ist dies
fraglos eine Wandlung nicht zuletzt der Ansprüdie, die der Wissenschaftler und
der wissenschaftlich orientierte Philosoph an ihre Tätigkeit und deren
Ergebnisse stellen zu dürfen glauben:

Mit den wachsenden Anforderungen an die instrumentale, insbesondere
prognostische Qualität und die wertbezogene Funktionalität der Erkenntnisgebilde
ist ein rasches Dahinschwinden der klassisch-erkenntnistheoretischen Auffassung
verbunden, die am Ideal der inten tionslos- wertfreien, auf objektive
„Realitätsabbildung" zielenden Erkenntnis orientiert war. Die
Forschergeneration, aus der heraus dieses Ideal noch in den Beginn der zweiten
Hälfte unseres Jahrhunderts hineinwirken konnte, ist fast ausgestorben. Die
meisten jungen Wissenschaftler unserer Tage begreifen gar nicht mehr jene Mühe
um Wahrheit und Ewigkeit, um Letzrbegründung und Objektivität, die für die
meisten der Älteren schlechterdings leitend und maßgebend war.

[Nicht, daß es jetzt keine „metaphysischen" Bedürfnisse mehr in Dingen des
Wissens gäbe! Aber diese Bedürfnisse und Antriebe sind ««zentriert. Der
menschferne rationalistische Dogmatismus und Objektivismus ist, auch noch in
seinen kriti(zisti)schen und (quasi-) pragmatischen Fortsetzungen von Kant bis
Popper, zerfallen. Das neue Zentrum einer total säkularisierten „metaphysischen"
Sehnsucht ist die Gesellschaft oder vielmehr das vergesellschaftete Ich, und das
Grundthema dieser Sehnsucht lautet „Emanzipation". Damit ist der Kampf gegen die
Leiden der tatsächlich oder vermeintlich „Unterpriviligierten" gemeint, der in
der Hauptsache Kampf ist gegen das jeweilige „Establishment". Erklärt
parteilich, stützt sich die neue „Metaphysik" auf soziale Gerechtigkeit. Dieser
will sie alles unterordnen, auch den Grundwert der individuellen
Selbstverwirklichung. Ihre empirischen Evidenzen sind im Grunde Hoffnungen, und
die Starre der Unbelehrbarkeit macht sie gegenüber ihrer klassischen Vorgängerin
gleichsam zum Dogmatismus höherer Ordnung. Sie ist bereit, auch noch das kleine
Einmaleins zum Ausdruck falschen Bewußtseins und damit zur Unwissenschaft zu
erklären, wenn es sich als „repressives Instrument der Etablierten" erweist. —
Wahrscheinlich wird die bemerkenswerte Affinität einer offenbar wach- senden
Zahl von Intellektuellen zu solch „metaphysisch" verabsolutiertem Engagement
bestimmend oder doch wesentlich mitbestim- mend werden für die soziokulturelle
Entwicklung noch der nächsten Jahre.

Auf längere Sicht dürften jedoch zwangsläufig die geschidulidi gewachsenen
liberalen Formen der philosophischen Diskussion gegcnüba stii 01 htatx weithin
als unerträglich HUp£imdeo.äa kollekri visuschen Tendenzen überdauern. Dabei ist
natürlich vorausgesetzt, daß die gegenwärtige Menschheit aus verantwortlicher
Rationalität entwickelte und durchsetzbare Rezepte gegen eine Reihe
selbstzerstörerischer Krankheiten, nicht zuletzt gegen die Ideologie des
permanenten technisch-wirtschaitlichen Wachstums, zu linden vermag.]

Das erste Kapitel dieses Buches beschäftigt sich vor allem mit der
erkenntnistheoretischen Problematik des Modellbegriffs. Die dabei offenbar
werdende philosophische Grundeinstellung ist die des Pragmatikers
wahrheitsphilosophiseher Provenienz. Sublime Pragmatiker ähneln oft Atheisten,
die ihren Gott gesucht, aber nicht gefunden haben; oder deren Gott sich ihnen
vielleicht in beglückend verfremdeter Gestalt offenbart. Enttäuschung kann
allerdings in Befreiung ausmünden, Ent-bergung in neue Geborgenheiten führen. —

Es ist notwendig, einleitend festzustellen, daß die im zweiten und dritten
Kapitel In Angriff genommene Modelltheorie nicht mit der von A. Tarski
geschaffenen semantischen Modelltheorie identisch ist. Sie ist auch kein
Teilgebiet derselben. Der hier verwendete Modellbegriff ist erheblich weiter
gefaßt. Er schließt auf der formalwissenschaftlichen Seite die durch
Äquivalenzklassenbildung gewonnenen sogenannten abstrakten Strukturen der
Mathematik und andere „formale Absrraktionsmodelie" ebenso ein wie auf der
erfahrungswissenschaftlichen Seire die in großer Vielfalt auftretenden
empirischen Modelle, Unter ihn fallen auch iKe technischen Modelle. Als was
immer sonst alle diese Modelle betrachtet werden, sie erweisen sich als sowohl
abbildungstheoretisch wie auch in ihren pragmatischen Bezügen ein hei dich
erfaßbar.

Darin, daß hier der — außerhalb der formalen Wissenschaften bisher fast nur
intuitiv, ohne strenge Definition, verwendete — Modellbegriff in der
angedeuteten Allgemeinheit abbildungstheoretisch expliziert wird, unterscheidet
sich die Allgemeine Modelltheorie bereits im Grundansatz auch van denjenigen
wissenschaftstheoretischen Versuchen, die die empirischen Modelle, soweit sie
diese überhaupt m die Betrachtung einbeziehen, ausschließlich der (meta-)
mathematischen und semantischen Modellkonzeption unterwerfen. Die in Frage
stehenden Modelle werden nach der Auffassung der betreffenden
Wissenschaftstheoretiker als „Belegungsmodelle" oder „Realisationen"
präexistenter Theorien, d. h. als nicht-linguistische, nämlich mengentheoretisch
erfaßbare Interpretationen linguisti sehet Formgebilde aufgefaß[fn:1].

[fn:1] Repräsentativ für diese Gruppe von Forschern: P. Suppes, 1961, 1965. Vgl.
hier und im folgenden das Literaturverzeichnis, S. 363 ff.

Gegen die Übertragung des logisch-semantischen Modellbegriffs auf die
Erfahrungswissenschaften, so logisch befriedigend sie immer sein mag, ist
einzuwenden, daß sie dem weithin geübten wissenschaftlichen Sprachgebrauch in
keiner Weise gerecht wird. So würden zahlreiche Erkenntnisergebnisse, die im
abbildungstheoretischen Sinne durchaus als Modelle gelten, ausgeklammert, nur
weil für sie eine strenge Theorie, deren Belegungsmodelle sie wären, nicht oder
noch nicht explizit angegeben werden können. Ja, in vielen Fällen dienen
derartige empirische (und technische) Modellkonstruktionen gerade dem Aufbau und
der Entwicklung von Theorien. Hierin liegt vornehmlich ihr großer heuristischer
Wert. Scheint jene gegenständliche Beschränkung mithin wenig ratsam, so ist doch
andererseits bei dem hier bevorzugten Vorgehen die Gefahr einer
„Überhomogenisierung“ unterschiedlichster Modellbegriffe und damit der starken
Bedeutungsentleerung des resultierenden allgemeinen Modellbegriffs vorerst nicht
von der Hand zu weisen. Dieses mögliche Manko wird hier ausdrücklich in Kauf
genommen.

Bezüglich der letzt erwähnten außerordentlichen Extension des Modellbegriffs
steht nun die Allgemeine Modelltheorie keineswegs allein da. L. APOSTEL[fn:2]
hat schon 1961[fn:3] ein gleichfalls umfassendes, und zwar ebenfalls
abbildungstheoretisches Modellkonzept entwickelt. Seine vom algebraischen
Isomorphiebegriff ausgehenden sukzessiven „Liberalisierungen“, die schließlich
zu seinem allgemeinen Modellbegriff führen, sind indes nicht ohne Künstlichkeit.
Auch scheint sich APOSTEL ohne zwingende Gründe bereits im Ausgangspunkt zu
stark am mathematischen „Relationengebilde“ (vgl. den Abschnitt 2.3.4.2, S. 243
ff.) zu orientieren. Das vorliegende Buch geht eher einen umgekehrten Weg. In
ihm sind nichtsdestoweniger wertvolle Einzelinformationen aus der APOSTELschen
Arbeit berücksichtigt.

Was APOSTEL gegen Ende seiner Darlegungen[fn:4] bezüglich der Verwendung einer
formalen Pragmatik andeutet, ist in dem vorliegenden Buch in gewissem Umfang
ausgeführt worden. Der hierfür bislang wohl einzige brauchbare Ansatz stammt von
R. M. MARTIN[fn:5], der vor fast fünfzehn Jahren das inzwischen allerdings wenig
bearbeitete Forschungsgebiet einer streng formalisierten Pragmatischen Logik
überhaupt ins Leben gerufen hat. Einige Jahre später konnte er in Anlehnung an
jüngere werttheoretische Forschungen ansatzweise seine klassifikatorische
„Akzeptionspragmatik“ zu einer komparativen und auch bereits quantitativen
Pragmatik erweitern[fn:6]. Diese Untersuchungen sind noch nicht besonders ausgereift,
ihre vorläufigen Ergebnisse eignen sich jedoch nichtsdestoweniger für die hier
verfolgten modelltheoretischen Zwecke. Der ganze Forschungskomplex im Umkreis
von formaler Pragmatik und Allgemeiner Modelltheorie bedarf natürlich noch
eingehender Bearbeitung. Auch das vorliegende Buch ist eigentlich nur Wegweiser
in ein noch kaum betretenes Neuland.

[fn:2] L. APOSTEL, 1961.

[fn:3] Leider ist mir die in Anm. 2 zitierte Arbeit erst nach Erscheinen meines
Aufsatzes „Gedanken zu einer allgemeinen Theorie der Modelle“ (H.
STACHOWIAK, 1965) bekanntgeworden.

[fn:4] A. a. O., Anm. 2, p. 36.

[fn:5] R. M. MARTIN, 1959.

[fn:6] R. M. MARTIN, 1964.


Dementsprechend bewegen sich auch die im dritten Kapitel dieses Buches
unternommenen logischen Formalisierungen, verglichen etwa mit dem hohen
Formalisierungsstand der logisch-semantischen und mathematischen Modelltheorie,
nur in sehr engen Grenzen. Der verbale und deskriptive Anteil der Darstellung
überwiegt insgesamt noch stark. Dies hat allerdings seinen Grund nicht allein in
sachlichen Schwierigkeiten. Das vorwiegend verbale Gewand der Darstellung
erklärt sich auch aus der Rücksichtnahme auf solche der Mathematischen Logik
fernstehende Leser, die sich ohne den recht aufwendigen formalllogischen Apparat
in die Gedanken des Buches einarbeiten wollen. In der Tagesarbeit stehend
Erfahrungswissenschaftler und andere modelltheoretisch Interessierte, die sich
nicht überwiegend mit wissenschaftstheoretisch-logischen und
linguistisch-analytischen Fragen beschäftigen, sollen ohne großen Zeitaufwand
förderlichen Zugang zu den behandelten Gegenständen finden. Daher geht die
Darstellung auch nicht überwiegend deduktiv, sondern gleichsam in induktiver
Approximation vor. Dies kommt insbesondere darin zum Ausdruck, daß die zu
explorierenden Begriffe, auch und vor allem der allgemeine Modellbegriff, auf
verbaler Ebene erörtert, exemplifiziert und geklärt werden, bevor darangegangen
wird, sie, wo es möglich und vorteilhaft scheint, einer strengeren logischen
Explikation zu unterwerfen. Der zweite und der dritte
