#+title: Allgemeine Modelltheorie
#+author: Prof. Dr. phil. Herbert Stachowiak
#+LANGUAGE: de

* Colophon

Prof. Dr. phil. Herbert Stachowiak
Berlin --- Paderborn

Direktor des Instituts für Wissenschafts- und Planungstheorie des Forschungs-
und Entwicklungszentrums für objektivierte Lehr- und Lernverfahren GmbH.

Das Werk ist urheberrechtlich geschützt.
Die dadurch begründeten Rechte, insbesondere die der Übersetzung,
des Nachdruckes, der Entnahme von Abbildungen,
der Funksendung, der Wiedergabe auf photomechanischem
oder ähnlichem Wege und der Speiche mng in Datenverarbeitungsanlagen,
bleiben, auch bei nur auszugsweiser Verwertung, vorbehalten.

(C) 1973 by Springer-Verlag/Wien

Library of Congress Cataiog Card Number 73-75910

Printed in Austria

ISBN 3-211-81106-0 Springer-Verlag Wien --- New York
ISBN 0-387-81106-0 Springer-Verlag New York --- Wien

* Widmung

Meinem Vater
Adalbert Stachowiak
zum Gedächtnis

* Vorwort

Die vorliegende Untersuchung ist das Ergebnis langjähriger Studien im Umkreis
des Modellbegriffs. Sie begannen 1957 mit einem ersten systematischen
Orientierungsversuch („Uber kausale, konditionale und strukturelle
Erklärungsmodelle“, Philosophia Naturalis, Bd. IV, H. 4, 1957, p. 403— 433) und
führten über mehrere Stufen fortschreitender Systematisierung zu dem 1965
vorgelegten modelltheoretischen Konzept („Gedanken zu einer allgemeinen Theorie
der Modelle“, Studium Generale, 18. Jg., H. 7, 1965, p. 432— 463), das ich
schließlich auf die Fassung der jetzt vorliegenden „Allgemeinen Modelltheorie“
erweitern und präzisieren konnte. Ende 1969 folgte ich einer Einladung der
UNESCO, Paris, eine Studie über den Modellbegriff abzufassen. Diese Arbeit ist
inzwischen erschienen in dem Sammelwerk „Scientific Thought“, Band 9 der Reihe
New Babylon (Mouton/Unesco, Paris-The Hague, 1972). Sie ist zum Teil als
Vorentwurf des dritten Kapitels der „Allgemeinen Modelltheorie“ zu betrachten.
Andere eigene Veröffentlichungen, insbesondere auf erkenntnispsychologischem und
wissenschaftstheoretischem Gebiet, sind durch die erwähnten modelltheoretischen
Untersuchungen beeinflußt. An ihren Ergebnissen ist auch mein Buch „Denken und
Erkennen im kybernetischen Modell“ (Wien — New York: Springer, 2. Aufl., 1969)
orientiert.

Mit vielen meiner Leser — kritische Rezensenten inbegriffen — betrachte ich mich
als in einem umfassenden Gesprächs- und Arbeitszusammenhang verbunden. Daher sei
auch zu dem vorliegenden Werk die Bitte um Hinweise auf systematische Fehler,
Disproportionalitäten, bedenklich scheinende Wertsetzungen und sonstige
tatsächliche oder mögliche Mängel des Buches vorgetragen. Nur in solcher
Kommunikation kann auf einem Felde, zu dessen weiterer Bearbeitung die Kräfte
eines einzelnen nicht ausreichen, der vorgelegte Ansatz bereinigt, vertieft und
erweitert werden. Allen Helfern hieran Dank im voraus.

Bei der Abfassung des Manuskripts haben mir in der Anfangsphase meiner
modelltheorerischen Überlegungen Gespräche mit den Herren P. Gäng und Prof. Dr. D.
Wunderlich wertvolle Anregungen gegeben. Hierfür sei beiden Genannten
herzlich gedankt. Herrn Wunderlich bin ich darüber hinaus für seine oft bis ins
formale Detail reichende Hilfe bei der Erarbeitung des logisch-explikativen
Teils des dritten Kapitels und der darin vorkommenden Maßbestimmungen zu
besonderem Dank verpflichtet, Den Herren Prof. Dr. H. Pachale, Dipl.-Math.
Studienrat W.Krüger und Dipl.-Math. R.-B. Lüschow dünke ich für kritische
Durchsicht des Manuskripts, Herrn Krüger darüber hinaus für gründliches
Korrekturlesen. Die Anlage des Namenverzeichnissen sowie die sorgfältige
Fehlerdurchsicht des Literaturverzeichnisses und der Bibliographie verdanke ich
Herrn H. Radimersky. Herr Dr. G.Wersig hat mir dankenswerterweise seine sich
über ein Jahr erstreckende Hilfe in bibliographischen Recherchen zureit werden
lassen. Dankbar hervorzuheben habe ich endlich erneut die unentbehrliche
technisch-organisatorische UnterStützung durch meine langjährige Mitarbeiterin
Frau H. Stranz und meine Frau B. Stachowiak-Prästel.

Die Deutsche Forschungsgemeinschaft hat meine modelltheoretischen Bemühungen in
einer (aus persönlichen Gründen kritisch gewordenen) wichtigen Arbeitsphase
unterstützt, wofür ihr hier aufrichtig Dank gesagt sei.

Dem Springer-Verlag bin ich für Verständnis, Geduld und stets freundliches
Entgegenkommen treu verbunden.

Berlin, im Sommer 1973

Herbert Stachowiak

* Einleitung

Im wissenschaftlichen wie außerwissenschaftlichen Sprachgebrauch hat gegenwärtig
der Modellbegriff zunehmend Relevanz erlangt. Bei zahlreichen passenden — leider
auch unpassenden — Gelegenheiten ist von „Modellen“ die Rede. Das W ort Modell
wird ebenso gedankenlos fehlverwendet, wie man es als bewußt gewählten
wissenschaftlichen Terminus in Zusammenhängen findet, die das Bestreben erkennen
lassen, es mit einer streng explizierten oder wenigstens explizierbaren
Bedeutung zu verbinden. In der M athematik und Logik ist dies unter starker
Einschränkung seines Bedeutungsgehaltes realisiert, und einige Autoren, die
diese Einschränkung nicht für fruchtbar hielten, haben versucht, das Spezifische
des Modellbegriffs so zu charakterisieren, daß erkennbar wird, in welchem Sinne
sie diesen Begriff verstanden und verwendet wissen wollen. Auch Ansätze
taxionomischer Klassifikation von Modellen sind hier und dort zu finden. Bei den
meisten Autoren jedoch, die in mannigfaltigsten Bezügen von Modellen sprechen,
vermißt man weitgehend, wenn nicht gänzlich,
wissenschaftstheoretisch-methodologische Reflexion über den von ihnen zugrunde
gelegten Modellbegriff. Dessen Charakteristika können in solchen Fällen nur
indirekt aus den gebotenen Kontexten erschlossen werden.
